plugins.apply('jacoco')

jacoco {
    toolVersion = "0.8.12"
}

androidComponents {
    onVariants(selector().all()) { variant ->
        createVariantCoverage(variant)
    }
}

ext.excludes = [
        'android/**/*.*',
        '**/databinding/*Binding.*',
        '**/R.class',
        '**/R$*.class',
        '**/BuildConfig.*',
        '**/Manifest*.*',
        '**/Lambda$*.class',
        '**/Lambda.class',
        '**/*BR*.*',
        '**/*Companion*.*',
        '**/*Lambda.class',
        '**/*Lambda*.class',
        '**/*$Lambda$*.*',
        '**/*Test*.*',
]

def createVariantCoverage(variant) {
    def buildDir = project.layout.buildDirectory.get().asFile
    def variantName = variant.name
    def capitalizedVariantName = variantName.capitalize()
    def testTaskName = "test${capitalizedVariantName}UnitTest"

    tasks.register("${testTaskName}Coverage", JacocoReport) {
        dependsOn(testTaskName)
        group = "testing"
        description = "Generate Jacoco coverage report for ${capitalizedVariantName}."

        reports {
            html.required = true
            xml.required = true
            xml.outputLocation = file("${buildDir}/reports/jacoco/${name}/${name}.xml")
        }

        def classTree = fileTree(
                dir: "${buildDir}/intermediates/javac/${variantName}/classes",
                excludes: project.excludes
        ) + fileTree(
                dir: "${buildDir}/tmp/kotlin-classes/${variantName}",
                excludes: project.excludes
        ) + fileTree(
                dir: "${buildDir}/intermediates/kotlin_classes/${variantName}/classes",
                excludes: project.excludes
        )

        getClassDirectories().setFrom(classTree)

        getSourceDirectories().setFrom(files([
                "$project.projectDir/src/main/java",
                "$project.projectDir/src/${variantName}/java",
                "$project.projectDir/src/main/kotlin",
                "$project.projectDir/src/${variantName}/kotlin"
        ]))

        getExecutionData().setFrom(fileTree(
                dir: "${buildDir}/outputs/unit_test_code_coverage/${variantName}UnitTest",
                includes: ["*.exec"]
        ) + fileTree(
                dir: "${buildDir}/jacoco",
                includes: ["${testTaskName}.exec"]
        ))
    }
}