name: Main
on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
      - name: Build and run test
        run: bash ./gradlew build testDebugUnitTestCoverage
      - uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./DeviceMarketingNames/build/reports/jacoco/testDebugUnitTestCoverage/testDebugUnitTestCoverage.xml
